eureka:
  instance:
    hostname: localhost
    port: 9000
  client:
    registerWithEureka: true
    fetchResitry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-empty: 3000
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-catalog
          uri: lb://product-catalog
          predicates:
            - Path=/product/**
        - id: shopping-cart
          uri: lb://shopping-cart
          predicates:
            - Path=/cart/**
        - id: shopping-cart
          uri: lb://client-cart
          predicates:
            - Path=/clientcart/**
